### ISSUE TITLE
Quic Flood Attack

### ISSUE THREAD

**Issue by Masrik-Dahir** [cloudflare/quiche#1015] opened 2021-07-25 15:19 UTC
I am trying to initiate for quic flood attack on a host server on a virtual machine and save the CPU statistics from the host machine. I do not see any instruction on how to successfully send a quick packet. Also, is it possible to send spoofed quic packets using the repository.

**Comment by LPardue** [comment] 2022-08-11 18:05
Closing as dupe of #1021

**Closed by LPardue** 2022-08-11 18:05 UTC
Labels: question
