### ISSUE TITLE
examples/server doesn't change SCID after sending Retry packet.

### ISSUE THREAD

**Issue by zhanwang-sky** [cloudflare/quiche#607] opened 2020-07-24 07:56 UTC
C routine `examples/server.c` doesn't change SCID after sending Retry packet:
![d5495634dac41ede699ea57fb02c8f7](https://user-images.githubusercontent.com/6380117/88370013-ce333280-cdc3-11ea-8ab5-eb68881c5d38.png)

according to RFC, server should select a new SCID to send Initial packet once it previously initiated a Retry
![841be8a0d2e79913ab77080e4112edc](https://user-images.githubusercontent.com/6380117/88370055-e3a85c80-cdc3-11ea-8903-cb1222c93aa1.png)

currently C-API quiche_accept just takes two SCIDs:
```
// Creates a new server-side connection.
quiche_conn *quiche_accept(const uint8_t *scid, size_t scid_len, <== server generated SCID
                           const uint8_t *odcid, size_t odcid_len, <== client temporarily generated DCID
                           quiche_config *config);
```
I think this API is not sufficient to complete Retry-Initial-Handshake process.

**Comment by LPardue** [comment] 2020-07-30 12:40
The example text in the specification is not normative, there is no normative text that requires `S2` and `S3` be different values.

**Comment by ghedo** [comment] 2021-01-26 12:11
As per @LPardue's comment, this is not a bug, so closing.

**Closed by ghedo** 2021-01-26 12:11 UTC
