### ISSUE TITLE
quiche_conn_recv() ==-1 in http3-client.c on windows

### ISSUE THREAD

**Issue by foroughmajidi** [cloudflare/quiche#471] opened 2020-04-21 09:56 UTC
I got "failed to process packet" and "failed to read: No error" in client.c:

![Capture24](https://user-images.githubusercontent.com/51900859/79851740-9490fc80-837a-11ea-834c-1082418420e8.PNG)

And I got "failed to process packet=-1" and "failed to read in http3-client.
What should I check to fix this problem?
Thanks

**Comment by LPardue** [comment] 2020-04-21 11:11
This is a duplicate of the message on https://github.com/cloudflare/quiche/issues/467, please don't do that it creates noise.

**Closed by LPardue** 2020-04-21 11:11 UTC
