### ISSUE TITLE
example server can't handle http1

### ISSUE THREAD

**Issue by muelli** [cloudflare/quiche#29] opened 2019-04-05 10:15 UTC
When starting the example client and server with `--http1`, the server log writes:

```
[2019-04-05T10:12:45Z INFO  server] 5687c7b0ef36c31903268dfb0ac3e7e8 got GET request for "examples/root/foo HTTP/1.1" ("examples/root/foo HTTP/1.1") on stream 4
```

We can see that "HTTP/1.1" is taken as part of the path.
I guess that the intention is to strip that off the path.

**Comment by ghedo** [comment] 2019-04-08 16:17
The lack of HTTP/1.x support is actually on purpose, due to the fact that there's no specified mapping of HTTP/1.x on top of QUIC (the only HTTP mapping that exists for QUIC is HTTP/3).

The example client does support making HTTP/1.1 requests, but that was only because for a while our test server didn't support HTTP/3 (which it now does), so I've been thinking about removing the HTTP/1.1 support from the client as well.

That would leave us with HTTP/0.9, which we currently need to test functionality with other QUIC implementations, and HTTP/3 which is the official HTTP version that should be used with QUIC.

**Comment by ghedo** [comment] 2019-04-11 22:32
Closing since this is the expected behavior (also I now removed the last remnant of HTTP/1.1 in 3ceee44c1f055680ee2153aa14b2579a65944169), but thanks for the report!

**Closed by ghedo** 2019-04-11 22:32 UTC
