### ISSUE TITLE
Receiver cannot process packets and send ack properly in a lossy network

### ISSUE THREAD

**Issue by SJTU-Ysw** [cloudflare/quiche#489] opened 2020-04-30 08:26 UTC
I'm trying to use quiche C API to send HEVC bitstreams in a lossy network.  It worked fine at first, but after a while, the receiver stopped sending ack packets and could not process the received data correctly, i.e. `quiche_stream_iter_next(readable, &s)` cannot find a readable stream though the received packets are correct.

When I checked the log, I found that the blocks in ack info were gradually getting very large.

```
...
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13171
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16199529 len=1307 fin=false
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13173
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16202143 len=1307 fin=false
recv=12509 sent=6086 lost=0 rtt=4091959ns cwnd=14520000
quiche: 2923be84e16cd6ae529049f1f1bbe9eb tx pkt Short dcid=b0de0430c200d74bf41ea0c92f8f28e1 key_phase=false len=1331 pn=6082
quiche: 2923be84e16cd6ae529049f1f1bbe9eb tx frm ACK delay=1 blocks=[0..13, 15..30, 32..35, 37..82, 84..113, 115..122, 124..132, 134..155, 157..165, 167..186, 188..209, 211..224, 226..253, 255..289, 291..339, 341..355, 358..412, 414..415, 417..487, 490..499, 501..549, 551..581, 583..585, 587..626, 628..645, 647..655, 657..671, 673..678, 680..706, 708..732, 734..744, 746..752, 754..776, 778..782, 784..816, 818..820, 822..857, 859..904, 906..921, 923..976, 978..979, 981..1007, 1009..1023, 1025..1042, 1044..1051, 1053..1129, 1131..1166, 1168..1191, 1193..1203, 1205..1253, 1255..1270, 1272..1280, 1282..1285, 1287..1295, 1297..1318, 1320..1338, 1340..1346, 1348..1373, 1375..1394, 1396..1422, 1424..1446, 1448..1467, 1469..1512, 1514..1569, 1571..1590, 1592..1599, 1601..1608, 1610..1619, 1621..1653, 1655..1658, 1660..1678, 1680..1716, 1718..1730, 1732..1733, 1735..1740, 1742..1744, 1746..1786, 1788..1820, 1822..1830, 1832..1837, 1839..1857, 1859..1867, 1869..1899, 1901..1910, 1913..1925, 1927..1939, 1941..2007, 2009..2026, 2028..2039, 2041..2087, 2089..2101, 2103..2106, 2108..2150, 2152..2155, 2157..2168, 2170..2178, 2180..2193, 2195..2216, 2218..2222, 2224..2225, 2227..2241, 2243..2252, 2254..2264, 2266..2272, 2274..2282, 2284..2286, 2288..2309, 2311..2318, 2320..2325, 2327..2330, 2332..2353, 2355..2356, 2358..2365, 2367..2381, 2383..2387, 2389..2396, 2398..2409, 2411..2419, 2421..2443, 2446..2456, 2458..2466, 2468..2469, 2471..2474, 2476..2480, 2482..2500, 2502..2520, 2522..2523, 2525..2545, 2547..2579, 2581..2582, 2584..2597, 2599..2628, 2630..2633, 2635..2653, 2655..2690, 2692..2726, 2728..2733, 2735..2740, 2742..2766, 2768..2838, 2840..2901, 2903..2942, 2944..3002, 3004..3066, 3068..3075, 3077..3097, 3099..3112, 3114..3133, 3135..3146, 3148..3178, 3180..3182, 3184..3193, 3195..3209, 3211..3251, 3253..3256, 3258..3276, 3278..3301, 3303..3329, 3331..3365, 3367..3390, 3392..3419, 3421..3477, 3479..3481, 3483..3531, 3533..3537, 3539..3550, 3552..3593, 3595..3603, 3605..3626, 3629..3637, 3639..3663, 3665..3675, 3678..3684, 3686..3687, 3689..3706, 3709..3721, 3723..3788, 3790..3799, 3801..3801, 3803..3812, 3814..3842, 3844..3848, 3850..3860, 3862..3872, 3874..3910, 3912..3932, 3934..3936, 3938..3973, 3975..3976, 3978..3978, 3980..4001, 4003..4010, 4012..4039, 4041..4048, 4050..4057, 4059..4113, 4115..4118, 4120..4132, 4134..4156, 4158..4184, 4186..4205, 4207..4267, 4269..4274, 4276..4318, 4320..4328, 4331..4366, 4368..4408, 4410..4454, 4456..4467, 4469..4482, 4484..4484, 4486..4552, 4554..4596, 4598..4622, 4624..4638, 4640..4641, 4643..4660, 4662..4697, 4699..4738, 4740..4744, 4746..4768, 4770..4817, 4819..4828, 4830..4848, 4850..4857, 4859..4866, 4868..4871, 4873..4898, 4900..4930, 4932..4954, 4956..4970, 4972..4976, 4978..4982, 4984..4992, 4994..5072, 5074..5094, 5096..5101, 5103..5178, 5180..5181, 5183..5184, 5186..5215, 5217..5218, 5220..5221, 5223..5232, 5234..5247, 5249..5266, 5268..5289, 5291..5302, 5304..5307, 5309..5312, 5314..5330, 5332..5340, 5342..5362, 5364..5364, 5367..5373, 5375..5387, 5389..5391, 5393..5393, 5395..5417, 5419..5438, 5440..5449, 5451..5464, 5466..5470, 5472..5498, 5500..5509, 5511..5522, 5524..5547, 5550..5571, 5573..5593, 5595..5603, 5605..5606, 5608..5653, 5655..5664, 5666..5668, 5670..5680, 5682..5686, 5688..5729, 5731..5738, 5740..5785, 5787..5824, 5826..5840, 5842..5876, 5878..5927, 5929..5939, 5941..5981, 5983..5984, 5986..6022, 6024..6055, 6057..6073, 6075..6075, 6078..6087, 6089..6111, 6113..6177, 6179..6179, 6181..6214, 6216..6248, 6250..6253, 6255..6259, 6261..6295, 6297..6306, 6308..6317, 6319..6322, 6324..6330, 6332..6336, 6338..6387, 6389..6411, 6413..6419, 6421..6436, 6438..6442, 6444..6475, 6477..6529, 6531..6556, 6558..6602, 6604..6676, 6679..6729, 6731..6731, 6734..6747, 6749..6755, 6757..6761, 6763..6848, 6850..6885, 6887..6890, 6892..6944, 6946..6946, 6948..6960, 6962..6973, 6975..7025, 7027..7091, 7093..7102, 7104..7110, 7112..7163, 7165..7210, 7212..7231, 7233..7241, 7243..7259, 7261..7264, 7266..7354, 7356..7364, 7366..7389, 7391..7398, 7400..7456, 7458..7460, 7462..7538, 7540..7588, 7590..7593, 7595..7601, 7603..7603, 7605..7608, 7610..7610, 7612..7613, 7615..7616, 7618..7654, 7657..7660, 7662..7667, 7669..7671, 7673..7737, 7739..7741, 7743..7753, 7755..7762, 7764..7765, 7767..7789, 7791..7853, 7855..7862, 7864..7874, 7876..7901, 7903..7915, 7917..7917, 7919..7936, 7938..7939, 7941..7987, 7989..8020, 8022..8025, 8027..8033, 8035..8042, 8044..8096, 8098..8114, 8116..8117, 8119..8125, 8127..8136, 8138..8161, 8163..8166, 8168..8170, 8172..8191, 8193..8205, 8207..8233, 8235..8249, 8251..8260, 8262..8265, 8267..8274, 8276..8277, 8279..8280, 8282..8293, 8295..8339, 8341..8347, 8349..8404, 8406..8409, 8411..8416, 8418..8418, 8420..8433, 8435..8468, 8470..8511, 8513..8551, 8553..8553, 8555..8558, 8560..8564, 8566..8583, 8585..8593, 8595..8610, 8612..8618, 8620..8646, 8648..8661, 8663..8670, 8672..8680, 8682..8693, 8695..8696, 8698..8702, 8704..8714, 8716..8746, 8748..8770, 8772..8777, 8779..8780, 8782..8802, 8804..8828, 8830..8867, 8870..8889, 8891..8963, 8965..8990, 8992..9013, 9015..9043, 9045..9051, 9053..9058, 9060..9071, 9074..9088, 9090..9118, 9120..9120, 9122..9162, 9164..9212, 9214..9236, 9238..9281, 9283..9302, 9304..9319, 9321..9329, 9331..9348, 9351..9355, 9357..9365, 9367..9375, 9377..9386, 9388..9404, 9406..9444, 9446..9448, 9450..9473, 9475..9481, 9483..9488, 9490..9490, 9492..9523, 9525..9527, 9529..9544, 9546..9562, 9564..9582, 9584..9584, 9586..9588, 9590..9614, 9616..9620, 9622..9653, 9655..9669, 9671..9679, 9681..9701, 9703..9711, 9713..9728, 9730..9775, 9777..9798, 9800..9803, 9805..9836, 9838..9845, 9847..9850, 9852..9852, 9855..9880, 9882..9890, 9892..9926, 9928..9945, 9947..9975, 9977..10001, 10003..10022, 10025..10029, 10031..10042, 10044..10062, 10064..10098, 10100..10111, 10113..10119, 10121..10148, 10150..10154, 10156..10158, 10160..10219, 10221..10247, 10249..10284, 10286..10294, 10296..10337, 10339..10342, 10344..10355, 10357..10374, 10376..10397, 10399..10401, 10403..10409, 10411..10435, 10437..10451, 10453..10460, 10462..10463, 10465..10466, 10468..10475, 10477..10479, 10481..10511, 10513..10546, 10548..10590, 10592..10595, 10598..10631, 10633..10636, 10638..10638, 10640..10645, 10647..10656, 10658..10668, 10670..10676, 10678..10690, 10692..10701, 10703..10708, 10710..10747, 10749..10770, 10772..10802, 10805..10808, 10810..10819, 10821..10837, 10839..10871, 10873..10910, 10912..10912, 10914..10945, 10947..10961, 10963..10964, 10966..10975, 10977..10977, 10979..10983, 10985..11001, 11003..11009, 11011..11013, 11015..11027, 11029..11033, 11035..11066, 11068..11103, 11105..11109, 11111..11169, 11171..11187, 11189..11217, 11219..11243, 11245..11249, 11251..11253, 11255..11266, 11268..11268, 11270..11284, 11286..11287, 11289..11293, 11295..11332, 11334..11351, 11353..11396, 11398..11483, 11485..11485, 11487..11540, 11542..11545, 11547..11574, 11576..11607, 11609..11610, 11612..11617, 11619..11621, 11623..11630, 11632..11671, 11673..11693, 11695..11705, 11708..11727, 11729..11740, 11742..11768, 11770..11814, 11816..11870, 11872..11885, 11887..11891, 11893..11898, 11900..11926, 11928..11938, 11940..11962, 11964..11987, 11990..11993, 11995..12013, 12015..12015, 12017..12022, 12024..12028, 12030..12037, 12039..12056, 12058..12099, 12101..12107, 12109..12150, 12152..12160, 12162..12191, 12193..12206, 12208..12217, 12219..12231, 12233..12238, 12240..12322, 12324..12351, 12353..12373, 12375..12435, 12437..12453, 12455..12459, 12461..12494, 12496..12516, 12518..12518, 12521..12574, 12576..12598, 12600..12601, 12603..12617, 12619..12640, 12642..12654, 12656..12660, 12662..12664, 12666..12666, 12668..12688, 12690..12701, 12703..12731, 12733..12782, 12784..12815, 12817..12834, 12836..12850, 12852..12853, 12855..12868, 12870..12872, 12874..12910, 12912..12924, 12926..12927, 12929..12946, 12948..12955, 12957..12979, 12981..12982, 12984..13024, 13026..13047, 13049..13074, 13076..13080, 13082..13089, 13091..13120, 13122..13140, 13142..13171, 13173..13173]
quiche::recovery: 2923be84e16cd6ae529049f1f1bbe9eb timer=none latest_rtt=7.7994ms srtt=Some(4.091959ms) min_rtt=483.2us rttvar=2.844699ms loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520000 ssthresh=18446744073709551615 bytes_in_flight=0 delivered=1357 delivered_time=6.8636726s recent_delivered_packet_sent_time=6.8715227s app_limited_at_pkt=0 
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13175
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16204757 len=1307 fin=false
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13176
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16206064 len=1307 fin=false
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13177
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16207371 len=1307 fin=false
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13178
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16208678 len=1307 fin=false
recv=12513 sent=6087 lost=0 rtt=4091959ns cwnd=14520000
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13180
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16211292 len=1307 fin=false
recv=12514 sent=6087 lost=0 rtt=4091959ns cwnd=14520000
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13182
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16078812 len=1307 fin=false
recv=12515 sent=6087 lost=0 rtt=4091959ns cwnd=14520000
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13183
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16160319 len=1307 fin=false
recv=12516 sent=6087 lost=0 rtt=4091959ns cwnd=14520000
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx pkt Short dcid=2923be84e16cd6ae529049f1f1bbe9eb key_phase=false len=1333 pn=13184
quiche: 2923be84e16cd6ae529049f1f1bbe9eb rx frm STREAM id=4 off=16213689 len=1307 fin=false
recv=12517 sent=6087 lost=0 rtt=4091959ns cwnd=14520000
...
(no tx packets)
```
I fixed the cwnd of the cc algorithm to a large value, and both the sender and receiver were localhost.
I don't know if it's caused by the oversized content of the blocks. But why can't the receiver handle subsequent packets correctly?

**Comment by xanathar** [comment] 2020-04-30 21:27
Running in a similar issue with a *very* similar use case, though I'm on a modified codebase and trying to understand if it's my fault. (for the sake of discussion, I'm also running a sender sending to a receiver 1GB of data on a localhost socket, from C; only difference I'm working on datagrams extensions - that's why I assumed it was my fault).

In any case, doing so I spent a lot of time on debugging, dumping here what I learned in case it can help diagnosing it; sorry if it doesn't make sense, in which case please just ignore this :). 

It seems that the lock is caused by the receiver having a very fragmented ACK space, so that the `wire_len` of the ACK frame is greater than the `left` available space in the outgoing packet (and thus the packet gets discarded, and nothing is ever sent in receiver->sender direction).
How it goes into having a very fragmented ACK space is something I still have to understand, as it's definitely not clear to me.
In any case, as soon as it gets into this state, it cannot send ACKs anymore. 

At this point, the sender will get locked for another reason, that is, `bytes_in_flight` are greater than the `cwnd`. 
Now, `bytes in flight` can decrease for two reasons: 1) because of ACKs (unlikely, the other part is blocked, see above) or 2) because of lost packets are detected. 
But, `detect_lost_packets` is called only in two situations (there is a pattern here) 1) inside `on_ack_received` (again, acks are not received) and 2) on recovery timeouts, but only if `earliest_loss_time` has Some value. Turns out that the only point - as far as I can see - that can set `earliest_loss_time` is `detect_lost_packets` itself, so 2) is excluded for this sort of "loop", and 1) is excluded because ... acks.

Hope this helps the team.

**Comment by ghedo** [comment] 2020-05-01 07:08
Thanks for reporting and for debugging. I have made https://github.com/cloudflare/quiche/pull/491 which attempts to limit the number of packet number ranges that are tracked for sending ACKs. This has a number of benefits, including ensuring that ACK frames can always be sent, at least in theory...

Could you please test those changes to see if they help with your situation?

**Comment by SJTU-Ysw** [comment] 2020-05-01 13:13
@ghedo Yes, it works! Now the number of packet number tracked is limit to a reasonable size. Thanks for the quick response and help! Should I close this issue?

**Comment by ghedo** [comment] 2020-05-01 13:28
@SJTU-Ysw nice, thanks for testing. Let's leave the issue open until the PR is merged.

**Comment by xanathar** [comment] 2020-05-07 17:50
I know it's a bit late, but also fixes it on my side 👍

**Closed** 2020-05-11 13:22 UTC
