### ISSUE TITLE
By changing the congestion control in Quiche, will it impact NGINX server?

### ISSUE THREAD

**Issue by Samy432** [cloudflare/quiche#1454] opened 2023-03-24 17:09 UTC
Quiche is a basic server, without access log. If I change the congestion control in QUICHE, will NGINX use the same congestion control or it is an independent server?

**Comment by LPardue** [comment] 2023-03-27 05:26
seems like a dupe of #1455, so closing

**Closed by LPardue** 2023-03-27 05:26 UTC
