### ISSUE TITLE
Question about encryption

### ISSUE THREAD

**Issue by thebsv** [cloudflare/quiche#1724] opened 2024-02-21 05:54 UTC
Was wondering if each packet being sent is encrypted or is it just the handshake which is encrypted? Pardon me for my lack of understanding, just a newbie. Thanks

**Comment by LPardue** [comment] 2024-04-04 09:37
Your best best for information about the QUIC protocol is the RFCs or other technical writing around that topic. I'd start with https://datatracker.ietf.org/doc/html/rfc9000#name-protected-packets, which will provide your answers (TL;DR all packets have some form of protection).

Since this isn't a question about the quiche project itself, I'm closing the issue. But feel free to post questions about QUIC to the community - https://github.com/quicwg/base-drafts/blob/main/CONTRIBUTING.md#engaging-with-the-quic-community

**Closed** 2024-04-04 09:38 UTC

**Comment by zerobsv** [comment] 2024-04-04 09:41
None

**Comment by Leichesters** [comment] 2024-06-10 15:35
I can confirm that learning about those protocols in detail will help you understand everything much better.

For example, if you want to use http/3.0, you will use encryption by default. Cloudflare has written a blog about this too: https://www.cloudflare.com/learning/performance/what-is-http3/

Keep in mind though, just using _some sort of encryption_ doesn't necessarily mean you are _secure_. ROT13 for example is an "encryption" algorithm that works by shifting all characters and has been used in production for emails. However, it's trivially easy to break as you can literally brute force it very quickly by hand by just shifting everything.

AES the most widely used encryption algorithm uses fixed s boxes (nonlinear function) which means there is an inverse S-Box that allows this person to... well... read everything :) Knowing this inverse s box is pretty much half of the key, so this isn't very secure. Therefore I'd strongly suggest you to also study different encryption algorithms that use a key dependent s box rather than a static one. Take examples from Blowfish, Serpent, Twofish etc

This is just the tip of the iceberg but should help you get started :)

**Comment by zerobsv** [comment] 2024-06-14 17:05
None
